// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emjjfunetwczvpwyswxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtampmdW5ldHdjenZwd3lzd3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NzA3MzksImV4cCI6MjA3MTE0NjczOX0.TMLsXSf9Gmm9dbTYNyKGmszzKcZIoEo0wn2bjMFIBY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});